name: Enforce main source branch

on:
  pull_request_target:
    branches:
      - main

jobs:
  allow-only-dev:
    name: allow-only-dev
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Pull requests into main must come from dev. Current source: ${{ github.head_ref }}"
            exit 1
          fi
